version: '3.8'



services:

  web:

    image: nginx:alpine

    ports:

      - "8080:80"

    volumes:

      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:

      - app



  app:

    build: ./node-app

    environment:

      - MYSQL_HOST=db

      - MYSQL_USER=root

      - MYSQL_PASSWORD=password

      - MYSQL_DATABASE=todo_db

    depends_on:

      - db



  db:

    image: mysql:8.0

    environment:

      - MYSQL_ROOT_PASSWORD=password

    volumes:

      - ./node-app/init.sql:/docker-entrypoint-initdb.d/init.sql

      - db-data:/var/lib/mysql



volumes:

  db-data:


